require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: disable
  Exclude:
    - '**/**.yml'
    - '**/**.md'
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'
    - 'app/assets'
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'docs/**/*'
    - 'lib/*'
    - 'log/*'
    - 'node_modules/**/*'
    - 'pkg/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.7
  UseCache: true
Metrics/AbcSize:
  Max: 42
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 12
Layout/LineLength:
  AllowURI: true
  Enabled: false
Metrics/MethodLength:
  CountComments: false
  Max: 43
Metrics/ModuleLength:
  Max: 164
Metrics/PerceivedComplexity:
  Max: 14
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/HashEachMethods:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
# Style/FrozenStringLiteralComment:
#   Description: ">- Apply frozen_string_literal to the top of ruby files\nThis is for transitioniting from Ruby 2.3 to Ruby 3.0"
#   Enabled: false

##############################
# Rails specific
##############################
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/InverseOf:
  Enabled: false
  EnforcedStyle: implicit
